name: Vulncheck

on:
  schedule:
  - cron: '0 10 */14 * *'
permissions:
  contents: read
jobs:
  vuln:
    uses: lufia/workflows/.github/workflows/go-vulncheck.yml@87182a21e45d32572eea26d16b42baf1e5da0537 # v0.12.0
